application: webworthy
version: 1
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: common-apps/djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: common-apps/django/contrib/admin/media
  
- url: /images/(.*\.(gif|png|jpg|ico))
  expiration: "3650d"
  static_files: media/images/\1
  upload: media/images/(.*\.(gif|png|jpg|ico))

- url: /js/(.*\.(js))
  expiration: "3650d"
  static_files: media/js/\1
  upload: media/js/(.*\.(js))

- url: /css/(.*)
  expiration: "3650d"
  static_files: media/css/\1
  upload: media/css/(.*)
  
- url: /swf/(.*\.(swf))
  expiration: "3650d"
  static_files: media/swf/\1
  upload: media/swf/(.*\.(swf))

- url: /data/(.*)
  expiration: "3650d"
  static_files: media/data/\1
  upload: media/data/(.*)

- url: /.*
  script: common-apps/djangoappengine/main/main.py
